# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

before_script:
- psql -c 'create database test;' -U postgres

after_success:
- Rscript -e 'covr::codecov()'
